env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  main: ./dnsmasq.go
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    amd64: x86_64
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/google/dnsmasq_exporter
    description: dnsmasq_exporter is an exporter for Prometheus, allowing you to monitor/alert on the number of DHCP leases and various DNS statistics.
    maintainer: Google
    vendor: GoReleaser
    formats:
    - deb
    dependencies:
    - git
    recommends:
    - deb
